### ISSUE TITLE
format of audio_common_msgs/AudioData  (ros ticket #1)

### ISSUE THREAD

**Issue by ahendrix** [ros-drivers/audio_common#1]
Could you please describe the format of the data field in the messages created by an audio_capture node (audio_common_msgs/AudioData)? 

From what I could tell, the output is written from a gst.Buffer with entries of type signed long. However, this is strange because the number of bytes of the data field is sometimes odd, when is should be a multiple of 4 (the size of a long). 

In the end, I need to obtain the audio data with respect to time from rosbags of the output of an audio_capture node.

trac data:
- Owner: **somebody**
- Reporter: **kstrabala**
- Reported at: **Wed Aug  3 23:07:41 2011**
- URL: https://kforge.ros.org/audiocommon/trac//ticket/1

**Comment by himanshuwalia** [comment]
Hi, 
I am trying to capture audio via a microphone, i have successful in capturing the audio as mp3 as also extracting the ros messages back to mp3 format, but i would like to extract them and save them as .wav format, while capturing i have given the argument for format as wave, it is successfully saving the rosbag file. 
Could you please help me with the extraction part from rosbag to .wav file.

**Comment by fabioreway** [comment]
> Hi,
> I am trying to capture audio via a microphone, i have successful in capturing the audio as mp3 as also extracting the ros messages back to mp3 format, but i would like to extract them and save them as .wav format, while capturing i have given the argument for format as wave, it is successfully saving the rosbag file.
> Could you please help me with the extraction part from rosbag to .wav file.

Hi himanhuwalia,
can you please share how you extracted your mp3 from the audio msgs sucessfully?
I'm still having trouble with that..
Thanks!
