### ISSUE TITLE
Unsupported media type error in audio_capture

### ISSUE THREAD

**Issue by piti-wity** [ros-drivers/audio_common#100]
I am trying to use the library on my Raspberry Pi 3 that is connected to an USB mic and to headphones through jack. Anyway I have the following issue: I attach a screenshot.
![schermata da 2017-09-28 15-40-15](https://user-images.githubusercontent.com/13849731/31132378-ec9286a2-a85c-11e7-8727-2824626c9802.png)

Please help me, thanks in advance.

**Comment by pjckoch** [comment]
Hi, I encountered the same issue on a Raspberry Pi Zero W. I tested it with the mic of the PSEye cam. Capturing audio works on my laptop, but not on the Raspi. Settings were the same. Moreover, I can capture audio on the Raspi with my own driver that uses PyAudio.

I'm wondering though: Why did you choose the title of this ticket to be "... Could not open device for recording"? I think this is misleading. You should probably call it "...Unsupported media type".

**Comment by knorth55** [comment]
can you try gstreamer from cui?
also can you try with `format=wave`?
if you cannot play audio from gstreamer cui, you cannot play it in `audio_capture`, too.

**Comment by knorth55** [comment]
no response, so I close this issue.
If you still have a problem, please reopen this issue

**Comment by thomaspeyrucain** [comment]
I had the same issue when launching : `roslaunch audio_capture capture.launch`
To fix it, make sure you have all this packages up to date :
`apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio`
Then check the configuration of your microphone with :
`arecord -l` To know what to put for hw:<card_number>,<device_number>
And with pulseaudio installed :
`pactl list short sinks` To know the number of channels, the sample_format and the sample_rate

Then if you launch with the correct config it should work :
`roslaunch audio_capture capture.launch channels:=2 sample_rate:=44100 device:=hw:1,0`

Check the audio topic to see if it is correctly working:
`rostopic echo /audio/audio`
