### ISSUE TITLE
audio_capture capture_wave.launch doesn't work

### ISSUE THREAD

**Issue by NishanthJKumar** [ros-drivers/audio_common#111]
Hi,
So I've been trying to use audio_capture in the wave format. When I try to run
`roslaunch audio_capture capture_wave.launch device:="hw:2,0"`
I get the following error:
`[ERROR] [1530115031.581276360]: gstreamer: Could not negotiate format`
Which causes the process to die...

Any help and suggestion is much appreciated!

**Comment by bkiefer** [comment]
Hi Nishanth, i found that wave capturing didn't work properly on my Ubuntu 18.04 / melodic installation, so i created a fix. Would you maybe like to check if it fixes your problem, too?

**Comment by knorth55** [comment]
can you check with current master branch and if the error still occurs?
