### ISSUE TITLE
window length

### ISSUE THREAD

**Issue by YimengZhu** [ros-drivers/audio_common#115]
Hi, First of all, thanks for the nice work. It helps my work a lot!

Is there any ways to set up the window length of the sampling? For example, the sample rate is 44100, can I set the window length as 1s so that in one ros message there would be 44100 values?

Thanks in advance!

**Comment by knorth55** [comment]
if you are using `audio_capture`, you can check it here.
https://github.com/ros-drivers/audio_common/blob/master/audio_capture/src/audio_capture.cpp#L179

**Comment by knorth55** [comment]
no response, so I close this issue.
If you still have a problem, please reopen this issue.
