### ISSUE TITLE
startWave does not work

### ISSUE THREAD

**Issue by kossumov** [ros-drivers/audio_common#117]
calling startWave() plays the wav file only once

Environment:
- Ubuntu 16.04
- ros-kinetic

Steps to reproduce:
- pull master branch
- change playWave to startWave in play.py
- call play.py on say-beep.wav

Result:
-plays once

Expected:
-plays repeatedly

**Comment by DaikiMaekawa** [comment]
Any update? I'm having exactly same problem with Kinetic on Ubuntu 16.04.

**Comment by knorth55** [comment]
this issue is solved by #131
