### ISSUE TITLE
Missing package dependencies

### ISSUE THREAD

**Issue by 5tan** [ros-drivers/audio_common#142]
After installing `ros-melodic-audio-common` in docker/ubuntu-18.04, sound output didn't work (no errors in console). 

I got sound working after installing additional packages: 
```
sudo apt install libgstreamer1.0-0 gstreamer1.0-pulseaudio gstreamer1.0-libav gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad
```

Similar issue: https://answers.ros.org/question/263077/sound_play-has-no-sound-and-no-errors/

**Comment by knorth55** [comment]
How can you reproduce this error?
Which node are you trying?

**Comment by 5tan** [comment]
> How can you reproduce this error?

I was following tutorial: http://wiki.ros.org/sound_play/Tutorials/ConfiguringAndUsingSpeakers
First: `rosrun sound_play soundplay_node.py`
Then: `rosrun sound_play say.py "hello world"`

> How can you reproduce this error?

Install `ros-melodic-audio-common` in some minimal VM, container or RPi. In my case there was no sound until I have installed those additional packages.

**Comment by knorth55** [comment]
can you give us commands to run your docker image?
I'm checking in my environment as below now.

```
docker  run --device /dev/snd     -e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native     -v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native     -v ~/.config/pulse/cookie:/root/.config/pulse/cookie     --group-add $(getent group audio | cut -d: -f3)     -it osrf/ros:melodic-desktop-bionic /bin/bash

# inside docker
apt update; apt install tmux ros-melodic-audio-common
# install pulseaudio
apt install pulseaudio
# i install these packages below, and it works
apt install gstreamer1.0-alsa
```

**Comment by 5tan** [comment]
> can you give us commands to run your docker image?
unfortunately no :( 

So you need to install manually `pulseaudio` and `gstreamer1.0-alsa`. Those packages are not listed as a `audio_common` package dependency, because other OS might require different "sound framework"?

**Comment by knorth55** [comment]
>unfortunately no :(

so, unfortunately, we cannot figure out your error is specific to your environment or not.
we can use either `pulseaudio` or `alsa`, it is not required.
however, `gstreamer1.0-alsa` is missing package dependency.

**Comment by knorth55** [comment]
I open a PR #144

**Comment by knorth55** [comment]
if you still have problem, please feel free to reopen this issue.

**Comment by iPwnXX** [comment]
I still can not solve the problem even after installing these dependencies.  no sound and no error, but `aplay` works
