### ISSUE TITLE
Feature Request: Support device by id

### ISSUE THREAD

**Issue by d-walsh** [ros-drivers/audio_common#153]
In other ROS device drivers it is possible to specify the device by id - which is very useful on systems that have multiple microphones connected. When I tried to pass the device id string to `audio_capture` it gave the error:
```
[/audio/audio_capture]: ros.audio_capture: gstreamer: Could not open audio device for recording.
```
The device that I want to use is: `/dev/snd/by-id/usb-xxxx-2314322-00`

**Comment by knorth55** [comment]
can you check this decice feature?
https://github.com/ros-drivers/audio_common/pull/87

it uses not usb device id but alsa device id.

**Comment by knorth55** [comment]
no response, so I will close this issue.
Feel free to reopen this issue.
