### ISSUE TITLE
Publish audio info data by AudioInfo in audio_capture node

### ISSUE THREAD

**Issue by knorth55** [ros-drivers/audio_common#161]
we can pass audio info by `AudioInfo.msg`.
First, we should publish audio info from `audio_capture` node.

cc. @708yamaguchi

**Comment by 708yamaguchi** [comment]
Thank you!

I'm busy right now and will be working on it in a week or two.

**Comment by 708yamaguchi** [comment]
I created https://github.com/ros-drivers/audio_common/pull/162
