### ISSUE TITLE
memory leak in audio_capture  (ros ticket #18)

### ISSUE THREAD

**Issue by ahendrix** [ros-drivers/audio_common#18]
I found a memory leak when not unrefing the buffer in the onNewBuffer() callback

here is a patch:

# HG changeset patch
# User Mike Bosse <mike.bosse@csiro.au>
# Date 2012-10-30 13:16:16 +1000
# Node ID 9ef7c8bd5fe24a635afc3668b5adfd90d658ceba
# Parent  41867e966e88da6df23521e150724be6901e0197
fixed memory leak

diff --git a/audio_capture/src/audio_capture.cpp b/audio_capture/src/audio_capture.cpp
--- a/audio_capture/src/audio_capture.cpp
+++ b/audio_capture/src/audio_capture.cpp
@@ -92,6 +92,8 @@
 
         server->publish(msg);
 
+       gst_buffer_unref(buffer);
+
         return GST_FLOW_OK;
       }

trac data:
 * Owner: **ahendrix**
 * Reporter: **mikebosse**
 * Reported at: **Mon Oct 29 20:29:18 2012**
 * URL: https://kforge.ros.org/audiocommon/trac//ticket/18

**Comment by trainman419** [comment]
Fixed by #56
