### ISSUE TITLE
Parameter name error

### ISSUE THREAD

**Issue by weeshal** [ros-drivers/audio_common#207]
Referring to [this code.](https://github.com/ros-drivers/audio_common/blob/2159f118a22e6841a51efb73fa209a313a6f2935/audio_capture/src/audio_capture.cpp#L24)
The use of tildes in parameter naming in ROS2 is redundant - seems like the code was translated to ROS2 verbatim but these can be removed:
`this->declare_parameter("~param")` => `this->declare_parameter("param")`

As a workaround I have to include the tilde as part of parameter name in the launch file but I suggest all the `~` are removed from `audio_capture.cpp` and elsewhere.

**Comment by knorth55** [comment]
can you make a PR?

**Comment by weeshal** [comment]
Yes here it is
https://github.com/ros-drivers/audio_common/pull/208

**Comment by knorth55** [comment]
Thank you! I merged!
