### ISSUE TITLE
Importing the sound_play module is slow

### ISSUE THREAD

**Issue by furushchev** [ros-drivers/audio_common#228]
Loading this module is slow especially on a machine with slow disk i/o.
I briefly profiled importing this library and found that the most of time is consumed on the initialization of the `FlitePlugin` class.
https://github.com/ros-drivers/audio_common/blob/master/sound_play/src/sound_play/flite_plugin.py#L17-L20
And as the class is initialized on the toplevel ( `__init__.py` ), this affects importing any class in this module.
https://github.com/ros-drivers/audio_common/blob/master/sound_play/src/sound_play/__init__.py#L34

<img width="289" alt="Screenshot 2023-04-10 at 2 25 38 PM" src="https://user-images.githubusercontent.com/1901008/231002067-aff2bf8f-258a-4baf-8cfd-3d3606ca1702.png">

**Comment by knorth55** [comment]
@furushchev 
Thank you!
The problem is that `rospack` is super slow for initialization.

As `app_manager`, we can share `rospack` object and  make the package faster.
https://github.com/PR2/app_manager/pull/52
