### ISSUE TITLE
Failed to find rosdep items on on OS:ubuntu version:10.04  (ros ticket #4)

### ISSUE THREAD

**Issue by ahendrix** [ros-drivers/audio_common#4]
Hi,

I would like to report that while following the tutorial steps for audio_common, ( http://www.ros.org/wiki/audio_common/Tutorials/Streaming%20audio ) ,  at the step for installing the ROS dependencies I encounter the error:

shanker@StudioXPSubuntu:~/Workspace/Aux-ROS-Packages/audio_common$ rosdep install audio_common
Failed to find rosdep gstreamer for package sound_play on OS:ubuntu version:10.04
Failed to find rosdep festival for package sound_play on OS:ubuntu version:10.04
Failed to find rosdep gstreamer for package audio_capture on OS:ubuntu version:10.04
Failed to find rosdep gstreamer for package audio_play on OS:ubuntu version:10.04
ERROR: ABORTING: Rosdeps [u'gstreamer', u'festival', u'gstreamer', u'gstreamer'] could not be resolved

I suppose the solution would be to ignore that and install these packages from Synaptic Package Manager for example. I have done so and installed 'libgstreamer0.10', 'libgstreamer0.10-dev', 'libgstreamermm-0.10-dev' and 'festival' from Synaptic Package Manager. 

I then followed the rest of the tutorial, and at the step "Testing your setup" upon execution of the command 'gst-launch-0.10 alsasrc ! audioconvert ! audioresample ! alsasink', I do hear my input being played back to me, with a little delay.

However, at the final step of using audio_capture and audio_play, I do not hear any output. I would also like to note that I have also recorded a bag file while running audio_capture, and the bag file did not have any data under the /audio topic. 

I wonder if the problem is with the aforementioned 'rosdep' issue, and that I have installed an incorrect dependency. On the other hand, could it be that I am using a Macbook and the soundcard in question is not handled by audio_capture?

Thank you,
Regards,
Shanker Keshavdas
Researcher , DFKI Saarbruecken,
Germany

trac data:
 * Owner: **nkoenig**
 * Reporter: **crystalbass17**
 * Reported at: **Sun Dec  4 11:11:38 2011**
 * URL: https://kforge.ros.org/audiocommon/trac//ticket/4

**Comment by trainman419** [comment]
Closing because Ubuntu 11.10 and 12.04 are no longer supported.
