### ISSUE TITLE
No Jade package

### ISSUE THREAD

**Issue by cmansley** [ros-drivers/audio_common#42]
There is currently no Jade Debian package yet. It would be great if we could simply bump the gbp release and rollout the nice new package. Right now, I am compiling it from scratch to use it with Jade.

**Comment by trainman419** [comment]
Ok; I'll work on this.

Release is pending at least one set of rosdep updates: https://github.com/ros/rosdistro/pull/8807

**Comment by trainman419** [comment]
Released: https://github.com/ros/rosdistro/pull/8808

**Comment by trainman419** [comment]
Release accepted.
