### ISSUE TITLE
Make an Indigo Branch

### ISSUE THREAD

**Issue by DLu** [ros-drivers/audio_common#48]
And then I will fix this:

    /opt/ros/indigo/lib/python2.7/dist-packages/sound_play/libsoundplay.py:89: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
      self.pub = rospy.Publisher('robotsound', SoundRequest)

**Comment by jack-oquin** [comment]
Why not fix it in master?

**Comment by mikeferguson** [comment]
master appears to be "groovy-devel" and is 52 commits behind hydro-devel. We could rename master to groovy-devel and create a new master that is hydro-devel + new stuff...

**Comment by jack-oquin** [comment]
Oops, good catch, Mike. 

If groovy-devel is currently the same as master (as I suspect), I would recommend merging everything up to hydro-devel into master, then start new development with that. 

Having a down-level master branch is just confusing.

**Comment by trainman419** [comment]
master synced with hydro-devel, indigo-devel branch created from current hydro branch.

**Comment by trainman419** [comment]
@DLu I'm pretty sure that was fixed by #45

**Comment by DLu** [comment]
Ok. It probably just isn't in the binary yet.
