### ISSUE TITLE
New Release for Indigo

### ISSUE THREAD

**Issue by DLu** [ros-drivers/audio_common#55]
Please :)

**Comment by trainman419** [comment]
yikes; it's been quite a while since I've done a release. Working on it.

**Comment by trainman419** [comment]
Released indigo-devel to ROS Indigo and Jade as version 0.2.8:

https://github.com/ros/rosdistro/pull/9593
https://github.com/ros/rosdistro/pull/9594

**Comment by DLu** [comment]
:speaker: :grinning:
