### ISSUE TITLE
How to play a wav file in linux C++ with the sound_play?

### ISSUE THREAD

**Issue by 78226415** [ros-drivers/audio_common#83]
Hi,
    Some codes like: rosrun sound_play test.py
    I run it in a command terminal, it is ok, and also heard some sound. I have a look at the codes in the test.py file, some codes like: soundhandle.playWave('say-beep.wav'), and the codes are written with python. I have got the source codes of audio_common-master, and saw a file name test.cpp in the folder sound_play/test, so i some codes like:
#include <sound_play/sound_play.h>
...
int main (int argc, char **argv)
{
...
sound_play::SoundClient sc;
sound_play::Sound s1 = sc.waveSound("/home/turtlebot/Desktop/test_baidu.wav");
s1.repeat();
sleepok(1, _nh);
s1.stop();
.....

     It build success, first i run the codes in a new command terminal: 
     rosrun sound_play soundplay_node.py
     it shows: [INFO] [WallTime: 1469860236.155931] sound_play node is ready to play sound
     then i run the codes in another command terminal : 
     rosrun hlf_robot main_program
     it shows: 
     [ WARN] [1469860254.500709545]: Sound command issued, but no node is subscribed to the topic. Perhaps you forgot to run soundplay_node.py
     After that, i run the codes in a new command terminal: rosrun sound_play test.py
     it is ok and i could hear the sound from it.
     I want to play a wav file in ROS C++ with sound_play.
     what should i do? Could some one help me?

thanks

**Comment by jack-oquin** [comment]
Questions like this belong on http://answers.ros.org.
