### ISSUE TITLE
How to fix a problem of sound_play for playing wave?

### ISSUE THREAD

**Issue by 78226415** [ros-drivers/audio_common#89]
Hi everyone,
     I want to play a wave file by using sound_play in c++, the codes like:
sound_play::SoundClient sc;
sc.playWave("/root/Desktop/test.wav");

and it shows:

[WARN] [WallTime: 1475855177.583316] Sound command issued, but no node is subscribed to the topic. Perhaps you forgot to run soundplay_node.py?

but i have run it before, like:

root@lgx-robot:~/hlf_ws# rosrun sound_play soundplay_node.py
[INFO] [WallTime: 1475853878.411334] sound_play node is ready to play sound

If i try to play it with python as is:
rosrun sound_play play.py /root/Desktop/test.wav

it is ok and you could hear the sound of the wave file.

And if i run the command: rosrun sound_play say.py "hello world"
it shows:

root@lgx-robot:~/hlf_ws# rosrun sound_play say.py "hello world"
Saying: hello world
Voice: voice_kal_diphone

and i could hear the sound.
My environment is ubuntu14.04 LTS, ros indigo.
what should i do? Should some one would help me?
thanks

**Comment by trainman419** [comment]
ROS answers is a more appropriate place for questions, and I see that you've already asked there: http://answers.ros.org/question/245308/how-to-fix-a-problem-of-sound_play-for-playing-wave-file-in-c/
