### ISSUE TITLE
Missing documentation on encoding of data in AudioData

### ISSUE THREAD

**Issue by rokusottervanger** [ros-drivers/audio_common#91]
I am trying to write a ROS node that subscribes to the AudioData topic published by the audio_capture node (wav), and stream the audio data into an artificial neural net for speech recognition. However, the encoding of the audio data is not clear from the message description, nor from any documentation.

At first I thought these messages contained 16bit samples, cut up into uint8s, but sometimes the number of bytes in a message is odd, so then how do I now where one sample starts and another stops?

**Comment by knorth55** [comment]
do you still have this issue?
if so, please join the discussion #136
