### ISSUE TITLE
interpret wav frames

### ISSUE THREAD

**Issue by arpit15** [ros-drivers/audio_common#94]
I am trying to threshold a waveform. However the waveform I obtain with just noise has very high values. I plot a single frame. 
![sound_sample](https://cloud.githubusercontent.com/assets/4703676/22601613/b035aeb8-ea0d-11e6-8656-40e15ccfed65.png)
I can clearly see the very low levels of noise in software like audacity whose waveform is as follows
![image](https://cloud.githubusercontent.com/assets/4703676/22601703/196e09de-ea0e-11e6-8443-0e56bd45cc39.png)
Please let me know how to get the waveform as displayed in audacity which I can use to process further.

Thank you

**Comment by jack-oquin** [comment]
This question is more appropriate to http://answers.ros.org.

Just a guess: might you be plotting an unsigned value as if it were signed?

**Comment by knorth55** [comment]
no response, so I will close this issue.
please feel free to reopen this.
