### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by shoemakerlevy9** [ros-drivers/audio_common#97]
Hi,

It would be nice to have volume control when playing sounds. I'm currently using the playWave function to play .wav files. I may try to add an optional volume field to this function but I am new to making open source contributions so help would be appreciated.

**Comment by trainman419** [comment]
Volume control was added in https://github.com/ros-drivers/audio_common/pull/51 , but since it's a change to the API it was only released for ROS Kinetic and newer, to prevent compatibility issues with older versions of ROS.

**Comment by shoemakerlevy9** [comment]
Great, I'm running ROS indigo which explains why I didn't see it in the code. Thank you.
